sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7.2

services:
  - docker
  - docker-compose

before_script:
  - docker --version
  - docker-compose --version
  - docker images -a
  - docker ps -a
  - docker network ls
  - docker volume ls

script:
  - docker-compose up -d

after_script:
  - docker images -a
  - docker ps -a
  - docker network ls
  - docker volume ls