sudo: required

matrix:
  include:
#    - os: linux
#      dist: trusty
    - os: osx
      osx_image: xcode8.2

services:
  - docker
  - docker-compose

before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcode-select –install && ruby -e “$(curl -fsSL && https://raw.githubusercontent.com/Homebrew/install/master/install)”; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install virtualbox && brew install docker && brew install boot2docker && boot2docker init && boot2docker up; fi
  - docker --version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew help ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew help ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install caskroom/cask/brew-cask ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install virtualbox; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install docker docker-machine; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then docker-machine start; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then docker-machine create -d virtualbox dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval "$(docker-machine env dev)"; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install docker; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boot2docker; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then boot2docker init; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then boot2docker up; fi

before_script:
  - docker --version
  - docker-compose --version
  - docker images -a
  - docker ps -a
  - docker network ls
  - docker volume ls

script:
  - docker-compose up -d

after_script:
  - docker images -a
  - docker ps -a
  - docker network ls
  - docker volume ls