language: java
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
#    - os: osx
#      env: OSX=10.12.1
#      osx_image: xcode8.2


script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then system_profiler SPSoftwareDataType; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install node; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install java; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y nodejs; fi
  - java -version
  - node -v
  - npm -v
  - npm install npm@latest -g
  - npm cache clean
  - node -v
  - npm -v

  - cd backend; pwd; ls -la
  - chmod +x ./gradlew
  - pwd; ./gradlew clean build
  - cd ../frontend; pwd; ls -la
  - npm run build -s

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker -v; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker-compose -v; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker info; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker images -a; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker ps -a; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker network ls; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker volume ls; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker-compose up -d; fi

after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker images -a; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker ps -a; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker volume ls; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker network ls; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker network inspect courses_net; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker info; fi