language: java
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: osx
      env: OSX=10.12.1
      osx_image: xcode8.2

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./travis/macos.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash ./macos.sh; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./travis/linux/script.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash ./travis/linux/script.sh; fi

  - uname -a
  - pwd
  - ls -la -a
  - java -version
  - node -v
  - npm -v
  - npm install npm@latest -g
  - npm cache clean
  - node -v
  - npm -v

  - cd backend; pwd; ls -la
  - chmod +x ./gradlew
  - pwd; ./gradlew clean build
  - cd ../frontend; pwd; ls -la
  - npm run build -s

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./travis/linux/docker_script.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash ./travis/linux/docker_script.sh; fi

after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./travis/linux/docker_afterscript.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash ./travis/linux/docker_afterscript.sh; fi
