language: java
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: osx
      env: OSX=10.12.1
      osx_image: xcode8.2


script:
  - uname -a
  - pwd
  - ls -la -a
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./macos.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash ./macos.sh; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash ./linux.sh; fi
  - java -version
  - node -v
  - npm -v
  - npm install npm@latest -g
  - npm cache clean
  - node -v
  - npm -v

  - cd backend; pwd; ls -la
  - chmod +x ./gradlew
  - pwd; ./gradlew clean build
  - cd ../frontend; pwd; ls -la
  - npm run build -s

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker -v; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker-compose -v; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker info; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker images -a; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker ps -a; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker network ls; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker volume ls; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker-compose up -d; fi

after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker images -a; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker ps -a; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker volume ls; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker network ls; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker network inspect courses_net; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker info; fi