language: java

sudo: required

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx

before_script:
  - chmod +x ./gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)