language: node_js
node_js:
  - 7

sudo: required

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx

before_install:
##    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 68576280
##    - sudo apt-add-repository "deb https://deb.nodesource.com/node_7.x $(lsb_release -sc) main"
##    - sudo apt-get update
##    - sudo apt-get install nodejs
##    - sudo apt-get update -y
##    - sudo curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
##    - sudo apt-get install -y nodejs npm
#    - sudo apt-get update
#    - sudo apt-get install -y clang-3.4
#    - java -version
#    - node -v
#    - npm -v

install:
    - sudo apt-get update
    - sudo apt-get install oracle-java8-installer
    - java -version
    - java -fullversion
    - sudo apt-get install oracle-java8-set-default
    - java -version
    - java -fullversion
    - npm install npm@latest -g

after_install:
    - java -version
    - java -fullversion
    - node -v
    - npm -v

before_script:
  - ls -la -a backend/
  - cd frontend; gradlew tasks
  - chmod +x backend/gradlew

script:
  - ./backend/gradlew check
  - node -v
  - npm -v
  - cd frontend; npm run build
#  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)