language: java

os:
  - linux
  - osx

sudo: required

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
#    - os: osx
#      osx_image: xcode7.2
#jdk:
#  - oraclejdk8

before_script:
  - chmod +x ./gradlew
  - chmod +x ./gradlew.bat
  
script:
  - gradle test
