language: java

sudo: required

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx

before_install:
    - sudo apt-get update -y
    - sudo curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
    - sudo apt-get install -y nodejs npm
    - node -v
    - npm -v

before_script:
  - chmod +x ./backend/gradlew

script:
  - ./backend/gradlew check
  - cd frontend; npm run build
#  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)