language: java

sudo: required

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      node_js: "7"
    - os: osx

before_install:
#    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 68576280
#    - sudo apt-add-repository "deb https://deb.nodesource.com/node_7.x $(lsb_release -sc) main"
#    - sudo apt-get update
#    - sudo apt-get install nodejs
#    - sudo apt-get update -y
#    - sudo curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
#    - sudo apt-get install -y nodejs npm
    - java -version
    - node -v
    - npm -v

before_script:
  - chmod +x ./backend/gradlew

script:
  - ./backend/gradlew check
  - cd frontend; npm run build
#  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)