sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8.2

services:
  - docker
  - docker-compose

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; xcode-select –install && ruby -e “$(curl -fsSL && https://raw.githubusercontent.com/Homebrew/install/master/install)”; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew cask install virtualbox && brew install docker && brew install boot2docker && boot2docker init && boot2docker up; fi

before_script:
  - docker --version
  - docker-compose --version
  - docker images -a
  - docker ps -a
  - docker network ls
  - docker volume ls

script:
  - docker-compose up -d

after_script:
  - docker images -a
  - docker ps -a
  - docker network ls
  - docker volume ls