version: 1.0.{build}
platform:
  - x86
  - x64
build:
  verbosity: detailed

install:
  - cup all -v
  - cinst -y docker docker-compose docker-machine virtualbox

build_script:
  - systeminfo
  - docker -v
  - docker-compose -v
  - dir
  - type docker-compose.yml
  - docker --version
  - docker-compose --version
  - docker-machine --version
  - docker-machine env default
  - docker-machine start default
  - docker info
  - docker-machine ls
#  - docker-machine env --shell powershell
#  - docker-machine env --shell powershell dev
#  - docker-machine env --shell powershell dev | iex
  - docker-compose up -d

#test_script:
#  - cd backend; gradlew.bat check

branches:
  only:
    - master

#cache:
#    - node_modules -> frontend\package.json

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
