version: 1.0.{build}
build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble

test_script:
  - gradlew.bat check

branches:
  only:
    - master

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
