version: 1.0.{build}
build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble

test_script:
  - gradlew.bat check
  - gradle test

branches:
  only:
    - master
cache:
  - C:\Users\appveyor\.gradle

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
