version: 1.0.{build}
#platform:
#  - x86
#  - x64

matrix:
  - platform: x86
  - platform: x64


init:
  - systeminfo

build:
  verbosity: quiet

install:
  - cup all -v
  - cinst -y jdk8 nodejs.install
  - npm install npm@latest -g
  - npm cache clean
  - refreshenv
  - java -version
  - node -v
  - npm -v

build_script:
  - cd backend
  - gradlew.bat build

test_script:
  - cd ../frontend
  - npm run build

branches:
  only:
    - master
