version: 1.0.{build}
platform:
  - x86
  - x64
build:
  verbosity: detailed

build_script:
  - @powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
  - choco install docker -y
  - choco install docker-compose -y
  - choco install docker-machine -y
  - docker-compose up -d

#test_script:
#  - cd backend; gradlew.bat check

branches:
  only:
    - master

#cache:
#    - node_modules -> frontend\package.json

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
