version: 1.0.{build}
platform:
  - x86
  - x64
build:
  verbosity: detailed

install:
  - cinst docker -y
  - cinst docker-compose -y
  - cinst docker-machine -y

build_script:
  - docker-compose up -d

#test_script:
#  - cd backend; gradlew.bat check

branches:
  only:
    - master

#cache:
#    - node_modules -> frontend\package.json

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
