version: 1.0.{build}
platform:
#  - x86
  - x64
build:
  verbosity: detailed

install:
  - cup all -v
  - cinst -y docker docker-compose docker-machine virtualbox

build_script:
  - systeminfo
  - docker --version
  - docker-compose --version
  - docker-machine --version
  - dir
  - dir C:\Users
  - setx DOCKER_CERT_PATH C:\Users\appveyor\.docker\machine\machines\default
  - setx DOCKER_HOST tcp://192.168.99.100:2376
  - setx DOCKER_MACHINE_NAME default
  - setx DOCKER_TLS_VERIFY 1
  - setx virtualbox C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
  - set
  - docker-machine ls
  - virtualbox startvm default
  - docker-machine create --driver virtualbox default
  - docker-machine ls
  - docker-machine env default
  - eval "$(docker-machine env default)"
  - type docker-compose.yml
  - docker-compose up -d

#test_script:
#  - cd backend; gradlew.bat check

branches:
  only:
    - master

#cache:
#    - node_modules -> frontend\package.json

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
