version: 1.0.{build}
platform:
#  - x86
  - x64
build:
  verbosity: detailed

install:
  - cup all -v
  - cinst -y jdk8 nodejs.install

test_script:
  - cd backend; gradlew.bat clean build
  - cd frontend; npm run build

branches:
  only:
    - master

#cache:
#    - node_modules -> frontend\package.json

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
