language: java
sudo: required
jdk:
  - oraclejdk8
before_install:
  - java -version
  - gradle -v
  - sudo apt-add-repository ppa:groovy-dev/groovy
  - sudo apt-get update
  - sudo apt-get install groovy
  - curl -V
  - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - node -v
  - sudo npm install npm@3.10.9 -g
  - npm -v
script:
  - gradle test
